packs <- c('askpass', 'cpp11', 'fontawesome', 'httr', 'munsell', 'rcmdcheck',
           'sass', 'urlchecker', 'backports', 'crayon', 'forcats', 'httr2',
           'openssl', 'RColorBrewer', 'scales', 'usethis', 'base64enc', 'credentials',
           'fs', 'ids', 'pillar', 'Rcpp', 'selectr', 'utf8', 'BH', 'curl', 'gargle',
           'ini', 'pkgbuild', 'readr', 'sessioninfo', 'uuid', 'bit', 'data.table',
           'generics', 'isoband', 'pkgconfig', 'readxl', 'shiny', 'vctrs', 'bit64', 'DBI',
           'gert', 'jquerylib', 'pkgdown', 'rematch', 'VGAM', 'blob', 'dbplyr',
           'ggplot2', 'jsonlite', 'pkgload', 'rematch2', 'sourcetools', 'viridisLite',
           'brew', 'desc', 'gh', 'knitr', 'praise', 'remotes', 'stringi', 'vroom', 'brio', 'devtools',
           'gitcreds', 'labeling', 'prettyunits', 'reprex', 'stringr', 'waldo', 'broom',
           'diffobj', 'glue', 'later', 'processx', 'rlang', 'sys', 'whisker', 'bslib', 'digest',
           'googledrive', 'lifecycle', 'profvis', 'rmarkdown', 'systemfonts', 'withr', 'cachem',
           'downlit', 'googlesheets4', 'lobstr', 'progress', 'R.methodsS3', 'testthat', 'xfun',
           'callr', 'dplyr', 'gtable', 'lubridate', 'promises', 'textshaping',
           'xml2', 'cellranger', 'dtplyr', 'haven', 'magrittr', 'pryr', 'R.oo', 'tibble', 'xopen',
           'cli', 'ellipsis', 'highr', 'MASS', 'ps', 'roxygen2', 'tidyr', 'xtable', 'clipr',
           'evaluate', 'hms', 'memoise', 'purrr', 'rprojroot', 'tidyselect', 'yaml', 'colorspace',
           'fansi', 'htmltools', 'mime', 'R6', 'rstudioapi', 'timechange', 'zip', 'commonmark',
           'farver', 'htmlwidgets', 'miniUI', 'ragg', 'R.utils', 'tinytex', 'conflicted', 'fastmap',
           'httpuv', 'modelr', 'rappdirs', 'rversions', 'tzdb')

install.packages(packs, repos = "https://cran.r-project.org/")
